version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
  pre_build:
    commands:
      - python --version
      - python manage.py collectstatic --noinput
      - pylint mysite/**/*.py || true
      - echo "pre build stage completed"
      - echo " Test Cases Started"
      - python manage.py test
      - echo "Test Cases Completed!!"
      - echo "Build stage completed!"
  build:
    commands:
      - echo "Build stage completed"

artifacts:
   files:
    - '**/*'