# Generated by Django 4.0.3 on 2022-04-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_billing_detail_state_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_detail',
            name='state_country',
            field=models.CharField(choices=[('gujarat', 'gujarat'), ('panjab', 'panjab'), ('rajasthan', 'rajasthan'), ('kerala', 'kerala')], max_length=100),
        ),
    ]
